// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DeviceLayoutDao is the data access object for table device_layout.
type DeviceLayoutDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns DeviceLayoutColumns // columns contains all the column names of Table for convenient usage.
}

// DeviceLayoutColumns defines and stores column names for table device_layout.
type DeviceLayoutColumns struct {
	Id        string //
	DeviceId  string //
	RoomId    string //
	StartTime string //
	EndTime   string //
	PushType  string //
	PushState string //
	Status    string //
	Layout    string //
	Version   string //
	CreatedAt string //
	UpdatedAt string //
}

// deviceLayoutColumns holds the columns for table device_layout.
var deviceLayoutColumns = DeviceLayoutColumns{
	Id:        "id",
	DeviceId:  "device_id",
	RoomId:    "room_id",
	StartTime: "start_time",
	EndTime:   "end_time",
	PushType:  "push_type",
	PushState: "push_state",
	Status:    "status",
	Layout:    "layout",
	Version:   "version",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewDeviceLayoutDao creates and returns a new DAO object for table data access.
func NewDeviceLayoutDao() *DeviceLayoutDao {
	return &DeviceLayoutDao{
		group:   "default",
		table:   "device_layout",
		columns: deviceLayoutColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DeviceLayoutDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DeviceLayoutDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DeviceLayoutDao) Columns() DeviceLayoutColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DeviceLayoutDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DeviceLayoutDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DeviceLayoutDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
