// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MeetingDatumDao is the data access object for table meeting_datum.
type MeetingDatumDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns MeetingDatumColumns // columns contains all the column names of Table for convenient usage.
}

// MeetingDatumColumns defines and stores column names for table meeting_datum.
type MeetingDatumColumns struct {
	Id               string //
	Uuid             string //
	MeetingUuid      string //
	UserUuid         string //
	PlatformUuid     string //
	SystemFileUuid   string //
	Name             string //
	Status           string //
	Sort             string //
	Mark             string //
	Reporter         string //
	ReportTime       string //
	IsJoinVote       string //
	IsSecret         string //
	StartTime        string //
	EndTime          string //
	PushTime         string //
	PushStatus       string //
	StartDatum       string //
	RoomSeatSchemeId string //
	ReporterField    string //
	UserShow         string //
	Attendee         string //
	UserDefined      string //
	AttendeeField    string //
	ReporterShow     string //
	UnitShow         string //
	UnitField        string //
	Unit             string //
	CreatedAt        string //
	UpdatedAt        string //
}

// meetingDatumColumns holds the columns for table meeting_datum.
var meetingDatumColumns = MeetingDatumColumns{
	Id:               "id",
	Uuid:             "uuid",
	MeetingUuid:      "meeting_uuid",
	UserUuid:         "user_uuid",
	PlatformUuid:     "platform_uuid",
	SystemFileUuid:   "system_file_uuid",
	Name:             "name",
	Status:           "status",
	Sort:             "sort",
	Mark:             "mark",
	Reporter:         "reporter",
	ReportTime:       "report_time",
	IsJoinVote:       "is_join_vote",
	IsSecret:         "is_secret",
	StartTime:        "start_time",
	EndTime:          "end_time",
	PushTime:         "push_time",
	PushStatus:       "push_status",
	StartDatum:       "start_datum",
	RoomSeatSchemeId: "room_seat_scheme_id",
	ReporterField:    "reporter_field",
	UserShow:         "user_show",
	Attendee:         "attendee",
	UserDefined:      "user_defined",
	AttendeeField:    "attendee_field",
	ReporterShow:     "reporter_show",
	UnitShow:         "unit_show",
	UnitField:        "unit_field",
	Unit:             "unit",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

// NewMeetingDatumDao creates and returns a new DAO object for table data access.
func NewMeetingDatumDao() *MeetingDatumDao {
	return &MeetingDatumDao{
		group:   "default",
		table:   "meeting_datum",
		columns: meetingDatumColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MeetingDatumDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MeetingDatumDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MeetingDatumDao) Columns() MeetingDatumColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MeetingDatumDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MeetingDatumDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MeetingDatumDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
