// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MeetingUserEnlistDao is the data access object for table meeting_user_enlist.
type MeetingUserEnlistDao struct {
	table   string                   // table is the underlying table name of the DAO.
	group   string                   // group is the database configuration group name of current DAO.
	columns MeetingUserEnlistColumns // columns contains all the column names of Table for convenient usage.
}

// MeetingUserEnlistColumns defines and stores column names for table meeting_user_enlist.
type MeetingUserEnlistColumns struct {
	Id          string //
	MeetingUuid string //
	UserUuid    string //
	Sort        string //
	Username    string //
	Unit        string //
	Dept        string //
	Position    string //
	Mobile      string //
	IsFirst     string //
	Mark        string //
	CreateTime  string //
	Status      string //
	CreatedAt   string //
	UpdatedAt   string //
}

// meetingUserEnlistColumns holds the columns for table meeting_user_enlist.
var meetingUserEnlistColumns = MeetingUserEnlistColumns{
	Id:          "id",
	MeetingUuid: "meeting_uuid",
	UserUuid:    "user_uuid",
	Sort:        "sort",
	Username:    "username",
	Unit:        "unit",
	Dept:        "dept",
	Position:    "position",
	Mobile:      "mobile",
	IsFirst:     "is_first",
	Mark:        "mark",
	CreateTime:  "create_time",
	Status:      "status",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewMeetingUserEnlistDao creates and returns a new DAO object for table data access.
func NewMeetingUserEnlistDao() *MeetingUserEnlistDao {
	return &MeetingUserEnlistDao{
		group:   "default",
		table:   "meeting_user_enlist",
		columns: meetingUserEnlistColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MeetingUserEnlistDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MeetingUserEnlistDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MeetingUserEnlistDao) Columns() MeetingUserEnlistColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MeetingUserEnlistDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MeetingUserEnlistDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MeetingUserEnlistDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
