// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MeetingFileFormatDao is the data access object for table meeting_file_format.
type MeetingFileFormatDao struct {
	table   string                   // table is the underlying table name of the DAO.
	group   string                   // group is the database configuration group name of current DAO.
	columns MeetingFileFormatColumns // columns contains all the column names of Table for convenient usage.
}

// MeetingFileFormatColumns defines and stores column names for table meeting_file_format.
type MeetingFileFormatColumns struct {
	Id          string //
	MeetingUuid string //
	UserUuid    string //
	Url         string //
	Path        string //
	Progress    string //
	Status      string //
	Time        string //
	Type        string //
	CreatedAt   string //
	UpdatedAt   string //
}

// meetingFileFormatColumns holds the columns for table meeting_file_format.
var meetingFileFormatColumns = MeetingFileFormatColumns{
	Id:          "id",
	MeetingUuid: "meeting_uuid",
	UserUuid:    "user_uuid",
	Url:         "url",
	Path:        "path",
	Progress:    "progress",
	Status:      "status",
	Time:        "time",
	Type:        "type",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewMeetingFileFormatDao creates and returns a new DAO object for table data access.
func NewMeetingFileFormatDao() *MeetingFileFormatDao {
	return &MeetingFileFormatDao{
		group:   "default",
		table:   "meeting_file_format",
		columns: meetingFileFormatColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MeetingFileFormatDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MeetingFileFormatDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MeetingFileFormatDao) Columns() MeetingFileFormatColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MeetingFileFormatDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MeetingFileFormatDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MeetingFileFormatDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
