// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MeetingQueueDao is the data access object for table meeting_queue.
type MeetingQueueDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns MeetingQueueColumns // columns contains all the column names of Table for convenient usage.
}

// MeetingQueueColumns defines and stores column names for table meeting_queue.
type MeetingQueueColumns struct {
	Id          string // 配置id
	MeetingUuid string // 会议uuid，meeting表的uuid
	Status      string // 状态：0未开始，1开会中，2结束，5执行失败
	EndTime     string // 结束时间
	CreatedAt   string // 创建时间
	UpdatedAt   string // 更新时间
}

// meetingQueueColumns holds the columns for table meeting_queue.
var meetingQueueColumns = MeetingQueueColumns{
	Id:          "id",
	MeetingUuid: "meeting_uuid",
	Status:      "status",
	EndTime:     "end_time",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewMeetingQueueDao creates and returns a new DAO object for table data access.
func NewMeetingQueueDao() *MeetingQueueDao {
	return &MeetingQueueDao{
		group:   "default",
		table:   "meeting_queue",
		columns: meetingQueueColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MeetingQueueDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MeetingQueueDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MeetingQueueDao) Columns() MeetingQueueColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MeetingQueueDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MeetingQueueDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MeetingQueueDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
