// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MicrophoneServerDao is the data access object for table microphone_server.
type MicrophoneServerDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns MicrophoneServerColumns // columns contains all the column names of Table for convenient usage.
}

// MicrophoneServerColumns defines and stores column names for table microphone_server.
type MicrophoneServerColumns struct {
	Id          string //
	RoomId      string //
	Ip          string //
	Port        string //
	MicMax      string //
	MicType     string //
	Volume      string //
	Alt         string //
	Bass        string //
	Sensitivity string //
	ClosingTime string //
	Mark        string //
	HostSn      string //
	Status      string //
	Register    string //
	DeviceType  string //
	CreatedAt   string //
	UpdatedAt   string //
}

// microphoneServerColumns holds the columns for table microphone_server.
var microphoneServerColumns = MicrophoneServerColumns{
	Id:          "id",
	RoomId:      "room_id",
	Ip:          "ip",
	Port:        "port",
	MicMax:      "mic_max",
	MicType:     "mic_type",
	Volume:      "volume",
	Alt:         "alt",
	Bass:        "bass",
	Sensitivity: "sensitivity",
	ClosingTime: "closing_time",
	Mark:        "mark",
	HostSn:      "host_sn",
	Status:      "status",
	Register:    "register",
	DeviceType:  "device_type",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewMicrophoneServerDao creates and returns a new DAO object for table data access.
func NewMicrophoneServerDao() *MicrophoneServerDao {
	return &MicrophoneServerDao{
		group:   "default",
		table:   "microphone_server",
		columns: microphoneServerColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MicrophoneServerDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MicrophoneServerDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MicrophoneServerDao) Columns() MicrophoneServerColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MicrophoneServerDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MicrophoneServerDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MicrophoneServerDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
