// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SystemBackupsDao is the data access object for table system_backups.
type SystemBackupsDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns SystemBackupsColumns // columns contains all the column names of Table for convenient usage.
}

// SystemBackupsColumns defines and stores column names for table system_backups.
type SystemBackupsColumns struct {
	Id         string //
	Name       string //
	CreateTime string //
	Time       string //
	FileSize   string //
	Type       string //
	Status     string //
	Path       string //
	SqlPath    string //
	Mark       string //
	CurrentUse string //
	CreatedAt  string //
	UpdatedAt  string //
}

// systemBackupsColumns holds the columns for table system_backups.
var systemBackupsColumns = SystemBackupsColumns{
	Id:         "id",
	Name:       "name",
	CreateTime: "create_time",
	Time:       "time",
	FileSize:   "file_size",
	Type:       "type",
	Status:     "status",
	Path:       "path",
	SqlPath:    "sql_path",
	Mark:       "mark",
	CurrentUse: "current_use",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewSystemBackupsDao creates and returns a new DAO object for table data access.
func NewSystemBackupsDao() *SystemBackupsDao {
	return &SystemBackupsDao{
		group:   "default",
		table:   "system_backups",
		columns: systemBackupsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SystemBackupsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SystemBackupsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SystemBackupsDao) Columns() SystemBackupsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SystemBackupsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SystemBackupsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SystemBackupsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
