// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SystemFileDao is the data access object for table system_file.
type SystemFileDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns SystemFileColumns // columns contains all the column names of Table for convenient usage.
}

// SystemFileColumns defines and stores column names for table system_file.
type SystemFileColumns struct {
	Id            string //
	ParentUuid    string //
	Uuid          string //
	PlatformUuid  string //
	MeetingUuid   string //
	UserUuid      string //
	Filename      string //
	Filesize      string //
	Filepath      string //
	TerminalId    string //
	UploadTime    string //
	Sort          string //
	FileUse       string //
	Mark          string //
	IsDirectory   string //
	AllUser       string //
	StartDatum    string //
	AllowDownload string //
	IsSecret      string //
	Status        string //
	CreatedAt     string //
	UpdatedAt     string //
}

// systemFileColumns holds the columns for table system_file.
var systemFileColumns = SystemFileColumns{
	Id:            "id",
	ParentUuid:    "parent_uuid",
	Uuid:          "uuid",
	PlatformUuid:  "platform_uuid",
	MeetingUuid:   "meeting_uuid",
	UserUuid:      "user_uuid",
	Filename:      "filename",
	Filesize:      "filesize",
	Filepath:      "filepath",
	TerminalId:    "terminal_id",
	UploadTime:    "upload_time",
	Sort:          "sort",
	FileUse:       "file_use",
	Mark:          "mark",
	IsDirectory:   "is_directory",
	AllUser:       "all_user",
	StartDatum:    "start_datum",
	AllowDownload: "allow_download",
	IsSecret:      "is_secret",
	Status:        "status",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewSystemFileDao creates and returns a new DAO object for table data access.
func NewSystemFileDao() *SystemFileDao {
	return &SystemFileDao{
		group:   "default",
		table:   "system_file",
		columns: systemFileColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SystemFileDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SystemFileDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SystemFileDao) Columns() SystemFileColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SystemFileDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SystemFileDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SystemFileDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
