// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TerminalDao is the data access object for table terminal.
type TerminalDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns TerminalColumns // columns contains all the column names of Table for convenient usage.
}

// TerminalColumns defines and stores column names for table terminal.
type TerminalColumns struct {
	Id                      string //
	TId                     string //
	Name                    string //
	Ip                      string //
	Mac                     string //
	Status                  string //
	RoomId                  string //
	Mark                    string //
	Type                    string //
	Config                  string //
	ConfigStatus            string //
	AssociatedVersionId     string //
	AssociatedVersionName   string //
	AssociatedVersionStatus string //
	Operate                 string //
	OsType                  string //
	GuardConfig             string //
	GuardUvId               string //
	GuardUvName             string //
	GuardUvStatus           string //
	DeviceSn                string //
	DeviceType              string //
	IpType                  string //
	Mask                    string //
	Gateway                 string //
	HostIp                  string //
	ClientIp                string //
	OptCounts               string //
	Concurrence             string //
	LifterType              string //
	SecondTid               string //
	CreatedAt               string //
	UpdatedAt               string //
}

// terminalColumns holds the columns for table terminal.
var terminalColumns = TerminalColumns{
	Id:                      "id",
	TId:                     "t_id",
	Name:                    "name",
	Ip:                      "ip",
	Mac:                     "mac",
	Status:                  "status",
	RoomId:                  "room_id",
	Mark:                    "mark",
	Type:                    "type",
	Config:                  "config",
	ConfigStatus:            "config_status",
	AssociatedVersionId:     "associated_version_id",
	AssociatedVersionName:   "associated_version_name",
	AssociatedVersionStatus: "associated_version_status",
	Operate:                 "operate",
	OsType:                  "os_type",
	GuardConfig:             "guard_config",
	GuardUvId:               "guard_uv_id",
	GuardUvName:             "guard_uv_name",
	GuardUvStatus:           "guard_uv_status",
	DeviceSn:                "device_sn",
	DeviceType:              "device_type",
	IpType:                  "ip_type",
	Mask:                    "mask",
	Gateway:                 "gateway",
	HostIp:                  "host_ip",
	ClientIp:                "client_ip",
	OptCounts:               "opt_counts",
	Concurrence:             "concurrence",
	LifterType:              "lifter_type",
	SecondTid:               "second_tid",
	CreatedAt:               "created_at",
	UpdatedAt:               "updated_at",
}

// NewTerminalDao creates and returns a new DAO object for table data access.
func NewTerminalDao() *TerminalDao {
	return &TerminalDao{
		group:   "default",
		table:   "terminal",
		columns: terminalColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TerminalDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TerminalDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TerminalDao) Columns() TerminalColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TerminalDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TerminalDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TerminalDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
