// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UpgradeVersionDao is the data access object for table upgrade_version.
type UpgradeVersionDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns UpgradeVersionColumns // columns contains all the column names of Table for convenient usage.
}

// UpgradeVersionColumns defines and stores column names for table upgrade_version.
type UpgradeVersionColumns struct {
	Id         string //
	UserUuid   string //
	Name       string //
	Versions   string //
	Url        string //
	Type       string //
	CurrentUse string //
	Mark       string //
	Deleted    string //
	Status     string //
	OsType     string //
	CreatedAt  string //
	UpdatedAt  string //
}

// upgradeVersionColumns holds the columns for table upgrade_version.
var upgradeVersionColumns = UpgradeVersionColumns{
	Id:         "id",
	UserUuid:   "user_uuid",
	Name:       "name",
	Versions:   "versions",
	Url:        "url",
	Type:       "type",
	CurrentUse: "current_use",
	Mark:       "mark",
	Deleted:    "deleted",
	Status:     "status",
	OsType:     "os_type",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewUpgradeVersionDao creates and returns a new DAO object for table data access.
func NewUpgradeVersionDao() *UpgradeVersionDao {
	return &UpgradeVersionDao{
		group:   "default",
		table:   "upgrade_version",
		columns: upgradeVersionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UpgradeVersionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UpgradeVersionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UpgradeVersionDao) Columns() UpgradeVersionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UpgradeVersionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UpgradeVersionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UpgradeVersionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
