// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserDao is the data access object for table user.
type UserDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns UserColumns // columns contains all the column names of Table for convenient usage.
}

// UserColumns defines and stores column names for table user.
type UserColumns struct {
	Id                   string //
	Uuid                 string //
	PlatformUuid         string //
	Account              string //
	Username             string //
	Password             string //
	Unit                 string //
	Dept                 string //
	Position             string //
	Salutatory           string //
	IsValid              string //
	IsTmp                string //
	UserType             string //
	Mark                 string //
	Theme                string //
	Headimg              string //
	Mobile               string //
	Email                string //
	FaceId               string //
	Sort                 string //
	SummitMeetingManager string //
	UserLogType          string //
	Deleted              string //
	ChangePassword       string //
	CreatedAt            string //
	UpdatedAt            string //
	LastPasswdUpdateTime string //
	Status               string //
}

// userColumns holds the columns for table user.
var userColumns = UserColumns{
	Id:                   "id",
	Uuid:                 "uuid",
	PlatformUuid:         "platform_uuid",
	Account:              "account",
	Username:             "username",
	Password:             "password",
	Unit:                 "unit",
	Dept:                 "dept",
	Position:             "position",
	Salutatory:           "salutatory",
	IsValid:              "is_valid",
	IsTmp:                "is_tmp",
	UserType:             "user_type",
	Mark:                 "mark",
	Theme:                "theme",
	Headimg:              "headimg",
	Mobile:               "mobile",
	Email:                "email",
	FaceId:               "face_id",
	Sort:                 "sort",
	SummitMeetingManager: "summit_meeting_manager",
	UserLogType:          "user_log_type",
	Deleted:              "deleted",
	ChangePassword:       "change_password",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
	LastPasswdUpdateTime: "last_passwd_update_time",
	Status:               "status",
}

// NewUserDao creates and returns a new DAO object for table data access.
func NewUserDao() *UserDao {
	return &UserDao{
		group:   "default",
		table:   "user",
		columns: userColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserDao) Columns() UserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
