// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// VideoFormatDao is the data access object for table video_format.
type VideoFormatDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns VideoFormatColumns // columns contains all the column names of Table for convenient usage.
}

// VideoFormatColumns defines and stores column names for table video_format.
type VideoFormatColumns struct {
	Id             string //
	SystemFileUuid string //
	Progress       string //
	Status         string //
	Path           string //
	Type           string //
	Force          string //
	Remain         string //
	CreatedAt      string //
	UpdatedAt      string //
}

// videoFormatColumns holds the columns for table video_format.
var videoFormatColumns = VideoFormatColumns{
	Id:             "id",
	SystemFileUuid: "system_file_uuid",
	Progress:       "progress",
	Status:         "status",
	Path:           "path",
	Type:           "type",
	Force:          "force",
	Remain:         "remain",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

// NewVideoFormatDao creates and returns a new DAO object for table data access.
func NewVideoFormatDao() *VideoFormatDao {
	return &VideoFormatDao{
		group:   "default",
		table:   "video_format",
		columns: videoFormatColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *VideoFormatDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *VideoFormatDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *VideoFormatDao) Columns() VideoFormatColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *VideoFormatDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *VideoFormatDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *VideoFormatDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
