// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalHardwareDao is internal type for wrapping internal DAO implements.
type internalHardwareDao = *internal.HardwareDao

// hardwareDao is the data access object for table hardware.
// You can define custom methods on it to extend its functionality as you wish.
type hardwareDao struct {
	internalHardwareDao
}

var (
	// Hardware is globally public accessible object for table hardware operations.
	Hardware = hardwareDao{
		internal.NewHardwareDao(),
	}
)

// Fill with you ideas below.
