// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingUserEnlistDao is internal type for wrapping internal DAO implements.
type internalMeetingUserEnlistDao = *internal.MeetingUserEnlistDao

// meetingUserEnlistDao is the data access object for table meeting_user_enlist.
// You can define custom methods on it to extend its functionality as you wish.
type meetingUserEnlistDao struct {
	internalMeetingUserEnlistDao
}

var (
	// MeetingUserEnlist is globally public accessible object for table meeting_user_enlist operations.
	MeetingUserEnlist = meetingUserEnlistDao{
		internal.NewMeetingUserEnlistDao(),
	}
)

// Fill with you ideas below.
