// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingSummaryDao is internal type for wrapping internal DAO implements.
type internalMeetingSummaryDao = *internal.MeetingSummaryDao

// meetingSummaryDao is the data access object for table meeting_summary.
// You can define custom methods on it to extend its functionality as you wish.
type meetingSummaryDao struct {
	internalMeetingSummaryDao
}

var (
	// MeetingSummary is globally public accessible object for table meeting_summary operations.
	MeetingSummary = meetingSummaryDao{
		internal.NewMeetingSummaryDao(),
	}
)

// Fill with you ideas below.
