// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingSummaryThirdDao is internal type for wrapping internal DAO implements.
type internalMeetingSummaryThirdDao = *internal.MeetingSummaryThirdDao

// meetingSummaryThirdDao is the data access object for table meeting_summary_third.
// You can define custom methods on it to extend its functionality as you wish.
type meetingSummaryThirdDao struct {
	internalMeetingSummaryThirdDao
}

var (
	// MeetingSummaryThird is globally public accessible object for table meeting_summary_third operations.
	MeetingSummaryThird = meetingSummaryThirdDao{
		internal.NewMeetingSummaryThirdDao(),
	}
)

// Fill with you ideas below.
