// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingPcMenuDao is internal type for wrapping internal DAO implements.
type internalMeetingPcMenuDao = *internal.MeetingPcMenuDao

// meetingPcMenuDao is the data access object for table meeting_pc_menu.
// You can define custom methods on it to extend its functionality as you wish.
type meetingPcMenuDao struct {
	internalMeetingPcMenuDao
}

var (
	// MeetingPcMenu is globally public accessible object for table meeting_pc_menu operations.
	MeetingPcMenu = meetingPcMenuDao{
		internal.NewMeetingPcMenuDao(),
	}
)

// Fill with you ideas below.
