// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingSignDao is internal type for wrapping internal DAO implements.
type internalMeetingSignDao = *internal.MeetingSignDao

// meetingSignDao is the data access object for table meeting_sign.
// You can define custom methods on it to extend its functionality as you wish.
type meetingSignDao struct {
	internalMeetingSignDao
}

var (
	// MeetingSign is globally public accessible object for table meeting_sign operations.
	MeetingSign = meetingSignDao{
		internal.NewMeetingSignDao(),
	}
)

// Fill with you ideas below.
