// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingEnrollMessageDao is internal type for wrapping internal DAO implements.
type internalMeetingEnrollMessageDao = *internal.MeetingEnrollMessageDao

// meetingEnrollMessageDao is the data access object for table meeting_enroll_message.
// You can define custom methods on it to extend its functionality as you wish.
type meetingEnrollMessageDao struct {
	internalMeetingEnrollMessageDao
}

var (
	// MeetingEnrollMessage is globally public accessible object for table meeting_enroll_message operations.
	MeetingEnrollMessage = meetingEnrollMessageDao{
		internal.NewMeetingEnrollMessageDao(),
	}
)

// Fill with you ideas below.
