// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingVoteItemDao is internal type for wrapping internal DAO implements.
type internalMeetingVoteItemDao = *internal.MeetingVoteItemDao

// meetingVoteItemDao is the data access object for table meeting_vote_item.
// You can define custom methods on it to extend its functionality as you wish.
type meetingVoteItemDao struct {
	internalMeetingVoteItemDao
}

var (
	// MeetingVoteItem is globally public accessible object for table meeting_vote_item operations.
	MeetingVoteItem = meetingVoteItemDao{
		internal.NewMeetingVoteItemDao(),
	}
)

// Fill with you ideas below.
