// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMeetingFileFormatDao is internal type for wrapping internal DAO implements.
type internalMeetingFileFormatDao = *internal.MeetingFileFormatDao

// meetingFileFormatDao is the data access object for table meeting_file_format.
// You can define custom methods on it to extend its functionality as you wish.
type meetingFileFormatDao struct {
	internalMeetingFileFormatDao
}

var (
	// MeetingFileFormat is globally public accessible object for table meeting_file_format operations.
	MeetingFileFormat = meetingFileFormatDao{
		internal.NewMeetingFileFormatDao(),
	}
)

// Fill with you ideas below.
