// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalMonitoringThresholdDao is internal type for wrapping internal DAO implements.
type internalMonitoringThresholdDao = *internal.MonitoringThresholdDao

// monitoringThresholdDao is the data access object for table monitoring_threshold.
// You can define custom methods on it to extend its functionality as you wish.
type monitoringThresholdDao struct {
	internalMonitoringThresholdDao
}

var (
	// MonitoringThreshold is globally public accessible object for table monitoring_threshold operations.
	MonitoringThreshold = monitoringThresholdDao{
		internal.NewMonitoringThresholdDao(),
	}
)

// Fill with you ideas below.
