// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalRegisterDao is internal type for wrapping internal DAO implements.
type internalRegisterDao = *internal.RegisterDao

// registerDao is the data access object for table register.
// You can define custom methods on it to extend its functionality as you wish.
type registerDao struct {
	internalRegisterDao
}

var (
	// Register is globally public accessible object for table register operations.
	Register = registerDao{
		internal.NewRegisterDao(),
	}
)

// Fill with you ideas below.
