// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalRoomSettingDao is internal type for wrapping internal DAO implements.
type internalRoomSettingDao = *internal.RoomSettingDao

// roomSettingDao is the data access object for table room_setting.
// You can define custom methods on it to extend its functionality as you wish.
type roomSettingDao struct {
	internalRoomSettingDao
}

var (
	// RoomSetting is globally public accessible object for table room_setting operations.
	RoomSetting = roomSettingDao{
		internal.NewRoomSettingDao(),
	}
)

// Fill with you ideas below.
