// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalRoomSeatUserDao is internal type for wrapping internal DAO implements.
type internalRoomSeatUserDao = *internal.RoomSeatUserDao

// roomSeatUserDao is the data access object for table room_seat_user.
// You can define custom methods on it to extend its functionality as you wish.
type roomSeatUserDao struct {
	internalRoomSeatUserDao
}

var (
	// RoomSeatUser is globally public accessible object for table room_seat_user operations.
	RoomSeatUser = roomSeatUserDao{
		internal.NewRoomSeatUserDao(),
	}
)

// Fill with you ideas below.
