// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalTerminalDao is internal type for wrapping internal DAO implements.
type internalTerminalDao = *internal.TerminalDao

// terminalDao is the data access object for table terminal.
// You can define custom methods on it to extend its functionality as you wish.
type terminalDao struct {
	internalTerminalDao
}

var (
	// Terminal is globally public accessible object for table terminal operations.
	Terminal = terminalDao{
		internal.NewTerminalDao(),
	}
)

// Fill with you ideas below.
