// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalTranslateSeatLangDao is internal type for wrapping internal DAO implements.
type internalTranslateSeatLangDao = *internal.TranslateSeatLangDao

// translateSeatLangDao is the data access object for table translate_seat_lang.
// You can define custom methods on it to extend its functionality as you wish.
type translateSeatLangDao struct {
	internalTranslateSeatLangDao
}

var (
	// TranslateSeatLang is globally public accessible object for table translate_seat_lang operations.
	TranslateSeatLang = translateSeatLangDao{
		internal.NewTranslateSeatLangDao(),
	}
)

// Fill with you ideas below.
