// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalTranslateSeatDao is internal type for wrapping internal DAO implements.
type internalTranslateSeatDao = *internal.TranslateSeatDao

// translateSeatDao is the data access object for table translate_seat.
// You can define custom methods on it to extend its functionality as you wish.
type translateSeatDao struct {
	internalTranslateSeatDao
}

var (
	// TranslateSeat is globally public accessible object for table translate_seat operations.
	TranslateSeat = translateSeatDao{
		internal.NewTranslateSeatDao(),
	}
)

// Fill with you ideas below.
