// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalUserFileDao is internal type for wrapping internal DAO implements.
type internalUserFileDao = *internal.UserFileDao

// userFileDao is the data access object for table user_file.
// You can define custom methods on it to extend its functionality as you wish.
type userFileDao struct {
	internalUserFileDao
}

var (
	// UserFile is globally public accessible object for table user_file operations.
	UserFile = userFileDao{
		internal.NewUserFileDao(),
	}
)

// Fill with you ideas below.
