// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygf/internal/dao/internal"
)

// internalUserOrganizationDao is internal type for wrapping internal DAO implements.
type internalUserOrganizationDao = *internal.UserOrganizationDao

// userOrganizationDao is the data access object for table user_organization.
// You can define custom methods on it to extend its functionality as you wish.
type userOrganizationDao struct {
	internalUserOrganizationDao
}

var (
	// UserOrganization is globally public accessible object for table user_organization operations.
	UserOrganization = userOrganizationDao{
		internal.NewUserOrganizationDao(),
	}
)

// Fill with you ideas below.
