// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigTheme is the golang structure for table config_theme.
type ConfigTheme struct {
	Id         uint        `json:"id"         ` //
	SysName    string      `json:"sysName"    ` //
	ThemeName  string      `json:"themeName"  ` //
	Path       string      `json:"path"       ` //
	Logo       string      `json:"logo"       ` //
	Background string      `json:"background" ` //
	Type       int         `json:"type"       ` //
	CreatedAt  *gtime.Time `json:"createdAt"  ` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` //
}
