// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Config is the golang structure for table config.
type Config struct {
	Id        int         `json:"id"        ` //
	Key       string      `json:"key"       ` //
	Value     string      `json:"value"     ` //
	Default   string      `json:"default"   ` //
	Mark      string      `json:"mark"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
