// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DeviceMsg is the golang structure for table device_msg.
type DeviceMsg struct {
	Id        uint        `json:"id"        ` //
	DeviceId  int         `json:"deviceId"  ` //
	Msg       string      `json:"msg"       ` //
	Time      int         `json:"time"      ` //
	Type      int         `json:"type"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
