// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DeviceCustom is the golang structure for table device_custom.
type DeviceCustom struct {
	Id           uint        `json:"id"           ` //
	IsShowDatum  int         `json:"isShowDatum"  ` //
	SkinColor    int         `json:"skinColor"    ` //
	BgImg        string      `json:"bgImg"        ` //
	Logo         string      `json:"logo"         ` //
	PropagateImg string      `json:"propagateImg" ` //
	Type         int         `json:"type"         ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
