// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Device is the golang structure for table device.
type Device struct {
	Id        uint        `json:"id"        ` //
	DeviceIp  string      `json:"deviceIp"  ` //
	DeviceMac string      `json:"deviceMac" ` //
	RoomId    int         `json:"roomId"    ` //
	Status    int         `json:"status"    ` //
	IsShowing int         `json:"isShowing" ` //
	IsPush    int         `json:"isPush"    ` //
	Type      int         `json:"type"      ` //
	Deleted   int         `json:"deleted"   ` //
	Ip        string      `json:"ip"        ` //
	Port      int         `json:"port"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
