// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FileFormat is the golang structure for table file_format.
type FileFormat struct {
	Id             uint        `json:"id"             ` //
	SystemFileUuid uint        `json:"systemFileUuid" ` //
	Progress       string      `json:"progress"       ` //
	Path           string      `json:"path"           ` //
	Status         uint        `json:"status"         ` //
	Type           uint        `json:"type"           ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
