// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Font is the golang structure for table font.
type Font struct {
	Id         uint        `json:"id"         ` //
	Name       string      `json:"name"       ` //
	Path       string      `json:"path"       ` //
	UploadTime *gtime.Time `json:"uploadTime" ` //
	Status     int         `json:"status"     ` //
	IsSysFont  int         `json:"isSysFont"  ` //
	CreatedAt  *gtime.Time `json:"createdAt"  ` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` //
}
