// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MeetingUserGroup is the golang structure for table meeting_user_group.
type MeetingUserGroup struct {
	UserUuid uint `json:"userUuid" ` //
	GroupId  uint `json:"groupId"  ` //
}
