// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingStatistics is the golang structure for table meeting_statistics.
type MeetingStatistics struct {
	Id               int         `json:"id"               ` //
	MeetingUuid      int64       `json:"meetingUuid"      ` //
	MeetingUserCount int         `json:"meetingUserCount" ` //
	MeetingDuration  int         `json:"meetingDuration"  ` //
	SavePaperCount   int         `json:"savePaperCount"   ` //
	MeetingTime      *gtime.Time `json:"meetingTime"      ` //
	StartTime        *gtime.Time `json:"startTime"        ` //
	EndTime          *gtime.Time `json:"endTime"          ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
