// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVoteUser is the golang structure for table meeting_vote_user.
type MeetingVoteUser struct {
	MeetingUuid     uint        `json:"meetingUuid"     ` //
	UserUuid        uint        `json:"userUuid"        ` //
	MeetingVoteUuid uint        `json:"meetingVoteUuid" ` //
	SystemFileUuid  uint        `json:"systemFileUuid"  ` //
	CreatedAt       *gtime.Time `json:"createdAt"       ` //
	UpdatedAt       *gtime.Time `json:"updatedAt"       ` //
}
