// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummaryThird is the golang structure for table meeting_summary_third.
type MeetingSummaryThird struct {
	MeetingSummaryId int         `json:"meetingSummaryId" ` //
	PhoneticTranId   int         `json:"phoneticTranId"   ` //
	Creator          string      `json:"creator"          ` //
	Modifier         string      `json:"modifier"         ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
