// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummary is the golang structure for table meeting_summary.
type MeetingSummary struct {
	Id                       uint        `json:"id"                       ` //
	MeetingUuid              uint        `json:"meetingUuid"              ` //
	SystemFileUuid           uint        `json:"systemFileUuid"           ` //
	UserUuid                 uint        `json:"userUuid"                 ` //
	Status                   uint        `json:"status"                   ` //
	IsUpdate                 int         `json:"isUpdate"                 ` //
	FileFormatSystemFileUuid uint        `json:"fileFormatSystemFileUuid" ` //
	MeetingDatumUuid         uint        `json:"meetingDatumUuid"         ` //
	CreatedAt                *gtime.Time `json:"createdAt"                ` //
	UpdatedAt                *gtime.Time `json:"updatedAt"                ` //
}
