// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingDatum is the golang structure for table meeting_datum.
type MeetingDatum struct {
	Id               uint        `json:"id"               ` //
	Uuid             uint        `json:"uuid"             ` //
	MeetingUuid      uint        `json:"meetingUuid"      ` //
	UserUuid         uint        `json:"userUuid"         ` //
	PlatformUuid     uint        `json:"platformUuid"     ` //
	SystemFileUuid   uint        `json:"systemFileUuid"   ` //
	Name             string      `json:"name"             ` //
	Status           uint        `json:"status"           ` //
	Sort             int         `json:"sort"             ` //
	Mark             string      `json:"mark"             ` //
	Reporter         string      `json:"reporter"         ` //
	ReportTime       string      `json:"reportTime"       ` //
	IsJoinVote       uint        `json:"isJoinVote"       ` //
	IsSecret         int         `json:"isSecret"         ` //
	StartTime        *gtime.Time `json:"startTime"        ` //
	EndTime          *gtime.Time `json:"endTime"          ` //
	PushTime         int         `json:"pushTime"         ` //
	PushStatus       int         `json:"pushStatus"       ` //
	StartDatum       int         `json:"startDatum"       ` //
	RoomSeatSchemeId int         `json:"roomSeatSchemeId" ` //
	ReporterField    string      `json:"reporterField"    ` //
	UserShow         int         `json:"userShow"         ` //
	Attendee         int         `json:"attendee"         ` //
	UserDefined      string      `json:"userDefined"      ` //
	AttendeeField    string      `json:"attendeeField"    ` //
	ReporterShow     int         `json:"reporterShow"     ` //
	UnitShow         int         `json:"unitShow"         ` //
	UnitField        string      `json:"unitField"        ` //
	Unit             string      `json:"unit"             ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
