// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingRecordContent is the golang structure for table meeting_record_content.
type MeetingRecordContent struct {
	Id          uint        `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	TerminalId  int         `json:"terminalId"  ` //
	HtmlContent string      `json:"htmlContent" ` //
	WordContent string      `json:"wordContent" ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
