// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSign is the golang structure for table meeting_sign.
type MeetingSign struct {
	Id             uint        `json:"id"             ` //
	MeetingUuid    uint        `json:"meetingUuid"    ` //
	SystemFileUuid uint        `json:"systemFileUuid" ` //
	SignStartTime  *gtime.Time `json:"signStartTime"  ` //
	Title          string      `json:"title"          ` //
	SignType       int         `json:"signType"       ` //
	Status         int         `json:"status"         ` //
	QrCode         string      `json:"qrCode"         ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
