// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVoteItem is the golang structure for table meeting_vote_item.
type MeetingVoteItem struct {
	Id                   int         `json:"id"                   ` //
	Name                 string      `json:"name"                 ` //
	IsMultiple           uint        `json:"isMultiple"           ` //
	IsTruename           uint        `json:"isTruename"           ` //
	IsLimit              uint        `json:"isLimit"              ` //
	IsLimitVal           string      `json:"isLimitVal"           ` //
	IsRate               uint        `json:"isRate"               ` //
	IsRateVal            uint        `json:"isRateVal"            ` //
	MoreThan             uint        `json:"moreThan"             ` //
	ScreenMode           uint        `json:"screenMode"           ` //
	ItemJson             string      `json:"itemJson"             ` //
	IsRemark             int         `json:"isRemark"             ` //
	VotingAuthentication uint        `json:"votingAuthentication" ` //
	IsNumberMic          uint        `json:"isNumberMic"          ` //
	CreatedAt            *gtime.Time `json:"createdAt"            ` //
	UpdatedAt            *gtime.Time `json:"updatedAt"            ` //
}
