// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingExtra is the golang structure for table meeting_extra.
type MeetingExtra struct {
	MeetingUuid     uint        `json:"meetingUuid"     ` //
	MenuTab         int         `json:"menuTab"         ` //
	NameplateCustom string      `json:"nameplateCustom" ` //
	WelcomeCustom   string      `json:"welcomeCustom"   ` //
	CreatedAt       *gtime.Time `json:"createdAt"       ` //
	UpdatedAt       *gtime.Time `json:"updatedAt"       ` //
}
