// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingQueue is the golang structure for table meeting_queue.
type MeetingQueue struct {
	Id          int         `json:"id"          ` // 配置id
	MeetingUuid uint        `json:"meetingUuid" ` // 会议uuid，meeting表的uuid
	Status      uint        `json:"status"      ` // 状态：0未开始，1开会中，2结束，5执行失败
	EndTime     *gtime.Time `json:"endTime"     ` // 结束时间
	CreatedAt   *gtime.Time `json:"createdAt"   ` // 创建时间
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` // 更新时间
}
