// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingService is the golang structure for table meeting_service.
type MeetingService struct {
	Id                  uint        `json:"id"                  ` //
	MeetingUuid         uint        `json:"meetingUuid"         ` //
	UserUuid            uint        `json:"userUuid"            ` //
	ServerId            uint        `json:"serverId"            ` //
	Content             string      `json:"content"             ` //
	Time                *gtime.Time `json:"time"                ` //
	IsConfirm           uint        `json:"isConfirm"           ` //
	Mark                string      `json:"mark"                ` //
	Status              uint        `json:"status"              ` //
	LaterHandleUserUuid uint        `json:"laterHandleUserUuid" ` //
	HandleUserUuid      uint        `json:"handleUserUuid"      ` //
	LaterHandleTime     *gtime.Time `json:"laterHandleTime"     ` //
	HandleTime          *gtime.Time `json:"handleTime"          ` //
	DeviceType          int         `json:"deviceType"          ` //
	CreatedAt           *gtime.Time `json:"createdAt"           ` //
	UpdatedAt           *gtime.Time `json:"updatedAt"           ` //
}
