// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingChat is the golang structure for table meeting_chat.
type MeetingChat struct {
	Id          uint        `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	UserUuid    uint        `json:"userUuid"    ` //
	MessageType uint        `json:"messageType" ` //
	Type        uint        `json:"type"        ` //
	Content     string      `json:"content"     ` //
	SendTime    *gtime.Time `json:"sendTime"    ` //
	AcceptUuid  string      `json:"acceptUuid"  ` //
	Mark        string      `json:"mark"        ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
