// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVote is the golang structure for table meeting_vote.
type MeetingVote struct {
	Id                   uint        `json:"id"                   ` //
	Uuid                 uint        `json:"uuid"                 ` //
	PlatformUuid         uint        `json:"platformUuid"         ` //
	MeetingUuid          uint        `json:"meetingUuid"          ` //
	MeetingDatumUuid     uint        `json:"meetingDatumUuid"     ` //
	SystemFileUuid       uint        `json:"systemFileUuid"       ` //
	VoteTitle            string      `json:"voteTitle"            ` //
	VoteName             string      `json:"voteName"             ` //
	StartTime            *gtime.Time `json:"startTime"            ` //
	EndTime              *gtime.Time `json:"endTime"              ` //
	Countdown            uint        `json:"countdown"            ` //
	VoteType             uint        `json:"voteType"             ` //
	IsMultiple           uint        `json:"isMultiple"           ` //
	IsTruename           uint        `json:"isTruename"           ` //
	Status               int         `json:"status"               ` //
	Mark                 string      `json:"mark"                 ` //
	IsSign               uint        `json:"isSign"               ` //
	IsPassRate           string      `json:"isPassRate"           ` //
	PassRate             float64     `json:"passRate"             ` //
	IsVoteTimeLimit      uint        `json:"isVoteTimeLimit"      ` //
	VoteTimeLimit        string      `json:"voteTimeLimit"        ` //
	IsMark               uint        `json:"isMark"               ` //
	ScreenMode           uint        `json:"screenMode"           ` //
	VotingAuthentication int         `json:"votingAuthentication" ` //
	VotingForce          int         `json:"votingForce"          ` //
	ScoreScore           string      `json:"scoreScore"           ` //
	ScoreType            int         `json:"scoreType"            ` //
	IsSetting            int         `json:"isSetting"            ` //
	RandomSort           int         `json:"randomSort"           ` //
	ForceVote            int         `json:"forceVote"            ` //
	AutoEnd              int         `json:"autoEnd"              ` //
	EditResult           int         `json:"editResult"           ` //
	CountVotes           int         `json:"countVotes"           ` //
	CreatedAt            *gtime.Time `json:"createdAt"            ` //
	UpdatedAt            *gtime.Time `json:"updatedAt"            ` //
}
