// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingBanner is the golang structure for table meeting_banner.
type MeetingBanner struct {
	Id             uint        `json:"id"             ` //
	Uuid           uint        `json:"uuid"           ` //
	PlatformUuid   uint        `json:"platformUuid"   ` //
	MeetingUuid    uint        `json:"meetingUuid"    ` //
	Title          string      `json:"title"          ` //
	Background     string      `json:"background"     ` //
	ModelFlag      uint        `json:"modelFlag"      ` //
	Datalayout     string      `json:"datalayout"     ` //
	Sort           uint        `json:"sort"           ` //
	BackgroundFlag uint        `json:"backgroundFlag" ` //
	BigFlag        uint        `json:"bigFlag"        ` //
	SmallFlag      int         `json:"smallFlag"      ` //
	BannerImg      string      `json:"bannerImg"      ` //
	PushTerminal   uint        `json:"pushTerminal"   ` //
	HtmlFormatId   uint        `json:"htmlFormatId"   ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
