// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummaryCountersign is the golang structure for table meeting_summary_countersign.
type MeetingSummaryCountersign struct {
	MeetingUuid        uint        `json:"meetingUuid"        ` //
	MeetingSummaryId   uint        `json:"meetingSummaryId"   ` //
	UserSystemFileUuid uint        `json:"userSystemFileUuid" ` //
	UserUuid           uint        `json:"userUuid"           ` //
	Status             uint        `json:"status"             ` //
	CreatedAt          *gtime.Time `json:"createdAt"          ` //
	UpdatedAt          *gtime.Time `json:"updatedAt"          ` //
}
