// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingFileFormat is the golang structure for table meeting_file_format.
type MeetingFileFormat struct {
	Id          uint        `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	UserUuid    uint        `json:"userUuid"    ` //
	Url         string      `json:"url"         ` //
	Path        string      `json:"path"        ` //
	Progress    string      `json:"progress"    ` //
	Status      uint        `json:"status"      ` //
	Time        *gtime.Time `json:"time"        ` //
	Type        uint        `json:"type"        ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
