// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingUserEnlist is the golang structure for table meeting_user_enlist.
type MeetingUserEnlist struct {
	Id          uint        `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	UserUuid    uint        `json:"userUuid"    ` //
	Sort        uint        `json:"sort"        ` //
	Username    string      `json:"username"    ` //
	Unit        string      `json:"unit"        ` //
	Dept        string      `json:"dept"        ` //
	Position    string      `json:"position"    ` //
	Mobile      string      `json:"mobile"      ` //
	IsFirst     uint        `json:"isFirst"     ` //
	Mark        string      `json:"mark"        ` //
	CreateTime  *gtime.Time `json:"createTime"  ` //
	Status      int         `json:"status"      ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
