// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MicrophoneServer is the golang structure for table microphone_server.
type MicrophoneServer struct {
	Id          uint        `json:"id"          ` //
	RoomId      uint        `json:"roomId"      ` //
	Ip          string      `json:"ip"          ` //
	Port        uint        `json:"port"        ` //
	MicMax      uint        `json:"micMax"      ` //
	MicType     int         `json:"micType"     ` //
	Volume      int         `json:"volume"      ` //
	Alt         int         `json:"alt"         ` //
	Bass        int         `json:"bass"        ` //
	Sensitivity int         `json:"sensitivity" ` //
	ClosingTime int         `json:"closingTime" ` //
	Mark        string      `json:"mark"        ` //
	HostSn      string      `json:"hostSn"      ` //
	Status      int         `json:"status"      ` //
	Register    int         `json:"register"    ` //
	DeviceType  int         `json:"deviceType"  ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
