// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MicrophoneServerTerminal is the golang structure for table microphone_server_terminal.
type MicrophoneServerTerminal struct {
	Id                 uint        `json:"id"                 ` //
	MicId              int         `json:"micId"              ` //
	Type               uint        `json:"type"               ` //
	Status             int         `json:"status"             ` //
	MicrophoneServerId uint        `json:"microphoneServerId" ` //
	Mark               string      `json:"mark"               ` //
	Mac                string      `json:"mac"                ` //
	ScreenIp           string      `json:"screenIp"           ` //
	DataType           int         `json:"dataType"           ` // 1:普通话筒，2:8512
	CreatedAt          *gtime.Time `json:"createdAt"          ` //
	UpdatedAt          *gtime.Time `json:"updatedAt"          ` //
}
