// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ModulLog is the golang structure for table modul_log.
type ModulLog struct {
	Id        int         `json:"id"        ` //
	ModulId   int         `json:"modulId"   ` //
	Type      int         `json:"type"      ` //
	UserUuid  uint        `json:"userUuid"  ` //
	Url       string      `json:"url"       ` //
	Path      string      `json:"path"      ` //
	Size      int         `json:"size"      ` //
	Status    int         `json:"status"    ` //
	Time      *gtime.Time `json:"time"      ` //
	StartTime *gtime.Time `json:"startTime" ` //
	EndTime   *gtime.Time `json:"endTime"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
