// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MonitoringThreshold is the golang structure for table monitoring_threshold.
type MonitoringThreshold struct {
	Id              uint        `json:"id"              ` //
	HarddiskPercent int         `json:"harddiskPercent" ` //
	MemoryPercent   int         `json:"memoryPercent"   ` //
	CpuPercent      int         `json:"cpuPercent"      ` //
	CreatedAt       *gtime.Time `json:"createdAt"       ` //
	UpdatedAt       *gtime.Time `json:"updatedAt"       ` //
}
