// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Monitoring is the golang structure for table monitoring.
type Monitoring struct {
	Id               uint        `json:"id"               ` //
	HarddiskUse      int         `json:"harddiskUse"      ` //
	Harddisk         int         `json:"harddisk"         ` //
	MemoryUse        int         `json:"memoryUse"        ` //
	Memory           int         `json:"memory"           ` //
	CpuPercent       int         `json:"cpuPercent"       ` //
	NetworkUpspeed   string      `json:"networkUpspeed"   ` //
	NetworkDownspeed string      `json:"networkDownspeed" ` //
	TerminalMac      string      `json:"terminalMac"      ` //
	LastViewTime     *gtime.Time `json:"lastViewTime"     ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
