// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// OperationLog is the golang structure for table operation_log.
type OperationLog struct {
	Id            int         `json:"id"            ` //
	UserUuid      uint        `json:"userUuid"      ` //
	Module        string      `json:"module"        ` //
	Operation     string      `json:"operation"     ` //
	OperationType string      `json:"operationType" ` //
	Detail        string      `json:"detail"        ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
