// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Organization is the golang structure for table organization.
type Organization struct {
	Id           uint        `json:"id"           ` //
	Uuid         uint        `json:"uuid"         ` //
	Puuid        uint        `json:"puuid"        ` //
	PlatformUuid uint        `json:"platformUuid" ` //
	Level        uint        `json:"level"        ` //
	Name         string      `json:"name"         ` //
	Sort         uint        `json:"sort"         ` //
	IsTmp        int         `json:"isTmp"        ` //
	Status       uint        `json:"status"       ` //
	Deleted      int         `json:"deleted"      ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
