// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PhoneticTranscriptionLog is the golang structure for table phonetic_transcription_log.
type PhoneticTranscriptionLog struct {
	Id        uint        `json:"id"        ` //
	Type      int         `json:"type"      ` //
	Status    int         `json:"status"    ` //
	Detailed  string      `json:"detailed"  ` //
	Creator   string      `json:"creator"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
