// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PlatformGuestTask is the golang structure for table platform_guest_task.
type PlatformGuestTask struct {
	Id               int         `json:"id"               ` //
	Name             string      `json:"name"             ` //
	MeetingStatus    int         `json:"meetingStatus"    ` //
	StartTime        *gtime.Time `json:"startTime"        ` //
	EndTime          *gtime.Time `json:"endTime"          ` //
	MeetingSlogan    string      `json:"meetingSlogan"    ` //
	Nameplate        string      `json:"nameplate"        ` //
	IsSecrect        int         `json:"isSecrect"        ` //
	Description      string      `json:"description"      ` //
	ModeratorName    string      `json:"moderatorName"    ` //
	CreateName       string      `json:"createName"       ` //
	MenuTab          int         `json:"menuTab"          ` //
	AuthorityJson    string      `json:"authorityJson"    ` //
	HostIp           string      `json:"hostIp"           ` //
	HostPlatformUuid uint        `json:"hostPlatformUuid" ` //
	HostPsIp         string      `json:"hostPsIp"         ` //
	HostPsPort       int         `json:"hostPsPort"       ` //
	HostMeetingUuid  uint        `json:"hostMeetingUuid"  ` //
	Status           int         `json:"status"           ` //
	Operate          int         `json:"operate"          ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
