// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Platform is the golang structure for table platform.
type Platform struct {
	Id        int         `json:"id"        ` //
	Uuid      uint64      `json:"uuid"      ` //
	Name      string      `json:"name"      ` //
	IsLocal   int         `json:"isLocal"   ` //
	Sysip     string      `json:"sysip"     ` //
	Sysport   int         `json:"sysport"   ` //
	Sysid     int         `json:"sysid"     ` //
	Status    int         `json:"status"    ` //
	Enable    int         `json:"enable"    ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
