// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PlatformPushTask is the golang structure for table platform_push_task.
type PlatformPushTask struct {
	Id           int         `json:"id"           ` //
	PlatformUuid uint64      `json:"platformUuid" ` //
	MeetingUuid  uint        `json:"meetingUuid"  ` //
	Status       int         `json:"status"       ` //
	Operate      int         `json:"operate"      ` //
	JoinTime     *gtime.Time `json:"joinTime"     ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
