// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PositionType is the golang structure for table position_type.
type PositionType struct {
	Id        uint        `json:"id"        ` //
	Name      string      `json:"name"      ` //
	Sort      int         `json:"sort"      ` //
	Deleted   int         `json:"deleted"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
