// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Position is the golang structure for table position.
type Position struct {
	Id             uint        `json:"id"             ` //
	PositionTypeId int         `json:"positionTypeId" ` //
	Name           string      `json:"name"           ` //
	Sort           int         `json:"sort"           ` //
	Deleted        int         `json:"deleted"        ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
