// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RecordingFile is the golang structure for table recording_file.
type RecordingFile struct {
	Id          uint        `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	TransId     int         `json:"transId"     ` //
	Type        int         `json:"type"        ` //
	FileName    string      `json:"fileName"    ` //
	FileSize    string      `json:"fileSize"    ` //
	FilePath    string      `json:"filePath"    ` //
	FileTime    string      `json:"fileTime"    ` //
	StartTime   *gtime.Time `json:"startTime"   ` //
	EndTime     *gtime.Time `json:"endTime"     ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
