// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSettingServe is the golang structure for table room_setting_serve.
type RoomSettingServe struct {
	Id        int         `json:"id"        ` //
	RoomId    int         `json:"roomId"    ` //
	Name      string      `json:"name"      ` //
	Src       string      `json:"src"       ` //
	IsSystem  int         `json:"isSystem"  ` //
	Sort      int         `json:"sort"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
