// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSetting is the golang structure for table room_setting.
type RoomSetting struct {
	Id        int         `json:"id"        ` //
	RoomId    int         `json:"roomId"    ` //
	Type      string      `json:"type"      ` //
	Content   string      `json:"content"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
