// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Room is the golang structure for table room.
type Room struct {
	Id             uint        `json:"id"             ` //
	Name           string      `json:"name"           ` //
	ServerId       uint        `json:"serverId"       ` //
	Roomlayout     string      `json:"roomlayout"     ` //
	Status         uint        `json:"status"         ` //
	Mark           string      `json:"mark"           ` //
	Roombackground string      `json:"roombackground" ` //
	BgWidth        int         `json:"bgWidth"        ` //
	BgHeight       int         `json:"bgHeight"       ` //
	TerminalConfig string      `json:"terminalConfig" ` //
	Transfer       int         `json:"transfer"       ` //
	Electronic     int         `json:"electronic"     ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
