// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSeat is the golang structure for table room_seat.
type RoomSeat struct {
	Id               uint        `json:"id"               ` //
	RoomId           int         `json:"roomId"           ` //
	UserUuid         uint        `json:"userUuid"         ` //
	RoomMicrophoneId int         `json:"roomMicrophoneId" ` //
	TerminalId       uint        `json:"terminalId"       ` //
	LifterTerminalId int         `json:"lifterTerminalId" ` //
	ElectronicId     uint        `json:"electronicId"     ` //
	SeatNo           uint        `json:"seatNo"           ` //
	Title            string      `json:"title"            ` //
	Status           int         `json:"status"           ` //
	Xway             int         `json:"xway"             ` //
	Yway             int         `json:"yway"             ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
