// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSeatScheme is the golang structure for table room_seat_scheme.
type RoomSeatScheme struct {
	Id          int         `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	Title       string      `json:"title"       ` //
	Type        int         `json:"type"        ` //
	Status      int         `json:"status"      ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
