// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Server is the golang structure for table server.
type Server struct {
	Id        uint        `json:"id"        ` //
	ServerId  int         `json:"serverId"  ` //
	Ip        string      `json:"ip"        ` //
	Port      uint        `json:"port"      ` //
	Status    uint        `json:"status"    ` //
	Flag      uint        `json:"flag"      ` //
	Mark      string      `json:"mark"      ` //
	Pid       uint        `json:"pid"       ` //
	Operate   uint        `json:"operate"   ` //
	Auth      uint        `json:"auth"      ` //
	Deleted   uint        `json:"deleted"   ` //
	Name      string      `json:"name"      ` //
	Content   string      `json:"content"   ` //
	IsHost    int         `json:"isHost"    ` //
	UvId      int         `json:"uvId"      ` //
	UvName    string      `json:"uvName"    ` //
	UvStatus  int         `json:"uvStatus"  ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
