// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemBackups is the golang structure for table system_backups.
type SystemBackups struct {
	Id         int         `json:"id"         ` //
	Name       string      `json:"name"       ` //
	CreateTime *gtime.Time `json:"createTime" ` //
	Time       *gtime.Time `json:"time"       ` //
	FileSize   float64     `json:"fileSize"   ` //
	Type       int         `json:"type"       ` //
	Status     int         `json:"status"     ` //
	Path       string      `json:"path"       ` //
	SqlPath    string      `json:"sqlPath"    ` //
	Mark       string      `json:"mark"       ` //
	CurrentUse int         `json:"currentUse" ` //
	CreatedAt  *gtime.Time `json:"createdAt"  ` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` //
}
