// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemFile is the golang structure for table system_file.
type SystemFile struct {
	Id            uint        `json:"id"            ` //
	ParentUuid    uint        `json:"parentUuid"    ` //
	Uuid          uint        `json:"uuid"          ` //
	PlatformUuid  uint        `json:"platformUuid"  ` //
	MeetingUuid   uint        `json:"meetingUuid"   ` //
	UserUuid      uint        `json:"userUuid"      ` //
	Filename      string      `json:"filename"      ` //
	Filesize      uint        `json:"filesize"      ` //
	Filepath      string      `json:"filepath"      ` //
	TerminalId    uint        `json:"terminalId"    ` //
	UploadTime    *gtime.Time `json:"uploadTime"    ` //
	Sort          uint        `json:"sort"          ` //
	FileUse       uint        `json:"fileUse"       ` //
	Mark          string      `json:"mark"          ` //
	IsDirectory   uint        `json:"isDirectory"   ` //
	AllUser       uint        `json:"allUser"       ` //
	StartDatum    uint        `json:"startDatum"    ` //
	AllowDownload int         `json:"allowDownload" ` //
	IsSecret      int         `json:"isSecret"      ` //
	Status        int         `json:"status"        ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
