// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Terminal is the golang structure for table terminal.
type Terminal struct {
	Id                      uint        `json:"id"                      ` //
	TId                     uint        `json:"tId"                     ` //
	Name                    string      `json:"name"                    ` //
	Ip                      string      `json:"ip"                      ` //
	Mac                     string      `json:"mac"                     ` //
	Status                  uint        `json:"status"                  ` //
	RoomId                  uint        `json:"roomId"                  ` //
	Mark                    string      `json:"mark"                    ` //
	Type                    uint        `json:"type"                    ` //
	Config                  string      `json:"config"                  ` //
	ConfigStatus            int         `json:"configStatus"            ` //
	AssociatedVersionId     int         `json:"associatedVersionId"     ` //
	AssociatedVersionName   string      `json:"associatedVersionName"   ` //
	AssociatedVersionStatus int         `json:"associatedVersionStatus" ` //
	Operate                 int         `json:"operate"                 ` //
	OsType                  int         `json:"osType"                  ` //
	GuardConfig             string      `json:"guardConfig"             ` //
	GuardUvId               int         `json:"guardUvId"               ` //
	GuardUvName             string      `json:"guardUvName"             ` //
	GuardUvStatus           int         `json:"guardUvStatus"           ` //
	DeviceSn                string      `json:"deviceSn"                ` //
	DeviceType              int         `json:"deviceType"              ` //
	IpType                  int         `json:"ipType"                  ` //
	Mask                    string      `json:"mask"                    ` //
	Gateway                 string      `json:"gateway"                 ` //
	HostIp                  string      `json:"hostIp"                  ` //
	ClientIp                string      `json:"clientIp"                ` //
	OptCounts               int         `json:"optCounts"               ` //
	Concurrence             string      `json:"concurrence"             ` //
	LifterType              int         `json:"lifterType"              ` //
	SecondTid               int         `json:"secondTid"               ` //
	CreatedAt               *gtime.Time `json:"createdAt"               ` //
	UpdatedAt               *gtime.Time `json:"updatedAt"               ` //
}
