// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TerminalConcurrence is the golang structure for table terminal_concurrence.
type TerminalConcurrence struct {
	Id          int         `json:"id"          ` //
	MeetingUuid uint        `json:"meetingUuid" ` //
	TotalUser   int         `json:"totalUser"   ` //
	ClientIds   string      `json:"clientIds"   ` //
	Usernames   string      `json:"usernames"   ` //
	UserMax     int         `json:"userMax"     ` //
	Type        int         `json:"type"        ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
