// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserOrganization is the golang structure for table user_organization.
type UserOrganization struct {
	Id                int  `json:"id"                ` //
	UserUuid          uint `json:"userUuid"          ` //
	OrganizationUuid  uint `json:"organizationUuid"  ` //
	OrganizationLevel int  `json:"organizationLevel" ` //
	Default           int  `json:"default"           ` //
	Binding           int  `json:"binding"           ` //
	Deleted           int  `json:"deleted"           ` //
}
