// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOtherLogin is the golang structure for table user_other_login.
type UserOtherLogin struct {
	Id        uint        `json:"id"        ` //
	UserUuid  uint        `json:"userUuid"  ` //
	Name      string      `json:"name"      ` //
	Pass      string      `json:"pass"      ` //
	Type      uint        `json:"type"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
