// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserFingerPrint is the golang structure for table user_finger_print.
type UserFingerPrint struct {
	Id          uint        `json:"id"          ` //
	UserUuid    uint        `json:"userUuid"    ` //
	Finger      string      `json:"finger"      ` //
	Fingerprint string      `json:"fingerprint" ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
