// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPosition is the golang structure for table user_position.
type UserPosition struct {
	Id         uint        `json:"id"         ` //
	UserUuid   uint64      `json:"userUuid"   ` //
	PositionId int         `json:"positionId" ` //
	Default    int         `json:"default"    ` //
	Deleted    int         `json:"deleted"    ` //
	CreatedAt  *gtime.Time `json:"createdAt"  ` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` //
}
