// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VideoFormat is the golang structure for table video_format.
type VideoFormat struct {
	Id             uint        `json:"id"             ` //
	SystemFileUuid uint        `json:"systemFileUuid" ` //
	Progress       string      `json:"progress"       ` //
	Status         uint        `json:"status"         ` //
	Path           string      `json:"path"           ` //
	Type           uint        `json:"type"           ` //
	Force          int         `json:"force"          ` //
	Remain         *gtime.Time `json:"remain"         ` //
	CreatedAt      *gtime.Time `json:"createdAt"      ` //
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` //
}
