// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigCustom is the golang structure of table config_custom for DAO operations like Where/Data.
type ConfigCustom struct {
	g.Meta         `orm:"table:config_custom, do:true"`
	Id             interface{} //
	SysName        interface{} //
	Logo           interface{} //
	Background     interface{} //
	DefaultSetting interface{} //
	Type           interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
