// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Config is the golang structure of table config for DAO operations like Where/Data.
type Config struct {
	g.Meta    `orm:"table:config, do:true"`
	Id        interface{} //
	Key       interface{} //
	Value     interface{} //
	Default   interface{} //
	Mark      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
