// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigTheme is the golang structure of table config_theme for DAO operations like Where/Data.
type ConfigTheme struct {
	g.Meta     `orm:"table:config_theme, do:true"`
	Id         interface{} //
	SysName    interface{} //
	ThemeName  interface{} //
	Path       interface{} //
	Logo       interface{} //
	Background interface{} //
	Type       interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
