// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DeviceLayout is the golang structure of table device_layout for DAO operations like Where/Data.
type DeviceLayout struct {
	g.Meta    `orm:"table:device_layout, do:true"`
	Id        interface{} //
	DeviceId  interface{} //
	RoomId    interface{} //
	StartTime *gtime.Time //
	EndTime   *gtime.Time //
	PushType  interface{} //
	PushState interface{} //
	Status    interface{} //
	Layout    interface{} //
	Version   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
