// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DeviceMsg is the golang structure of table device_msg for DAO operations like Where/Data.
type DeviceMsg struct {
	g.Meta    `orm:"table:device_msg, do:true"`
	Id        interface{} //
	DeviceId  interface{} //
	Msg       interface{} //
	Time      interface{} //
	Type      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
