// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Hardware is the golang structure of table hardware for DAO operations like Where/Data.
type Hardware struct {
	g.Meta        `orm:"table:hardware, do:true"`
	Id            interface{} //
	CpuPercent    interface{} //
	MemoryPercent interface{} //
	HarddiskSpace interface{} //
	TerminalMac   interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
