// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// HtmlFormat is the golang structure of table html_format for DAO operations like Where/Data.
type HtmlFormat struct {
	g.Meta      `orm:"table:html_format, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	MultiUuid   interface{} //
	Url         interface{} //
	Path        interface{} //
	Progress    interface{} //
	Status      interface{} //
	Type        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
