// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// LivePush is the golang structure of table live_push for DAO operations like Where/Data.
type LivePush struct {
	g.Meta         `orm:"table:live_push, do:true"`
	Id             interface{} //
	SystemFileUuid interface{} //
	Pid            interface{} //
	Progress       interface{} //
	Status         interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
