// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummaryThird is the golang structure of table meeting_summary_third for DAO operations like Where/Data.
type MeetingSummaryThird struct {
	g.Meta           `orm:"table:meeting_summary_third, do:true"`
	MeetingSummaryId interface{} //
	PhoneticTranId   interface{} //
	Creator          interface{} //
	Modifier         interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
