// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSignInfo is the golang structure of table meeting_sign_info for DAO operations like Where/Data.
type MeetingSignInfo struct {
	g.Meta         `orm:"table:meeting_sign_info, do:true"`
	Id             interface{} //
	MeetingUuid    interface{} //
	UserUuid       interface{} //
	SystemFileUuid interface{} //
	MeetingSignId  interface{} //
	Status         interface{} //
	SignTime       *gtime.Time //
	Assist         interface{} //
	DeviceType     interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
