// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummaryCountersign is the golang structure of table meeting_summary_countersign for DAO operations like Where/Data.
type MeetingSummaryCountersign struct {
	g.Meta             `orm:"table:meeting_summary_countersign, do:true"`
	MeetingUuid        interface{} //
	MeetingSummaryId   interface{} //
	UserSystemFileUuid interface{} //
	UserUuid           interface{} //
	Status             interface{} //
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
}
