// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingStatistics is the golang structure of table meeting_statistics for DAO operations like Where/Data.
type MeetingStatistics struct {
	g.Meta           `orm:"table:meeting_statistics, do:true"`
	Id               interface{} //
	MeetingUuid      interface{} //
	MeetingUserCount interface{} //
	MeetingDuration  interface{} //
	SavePaperCount   interface{} //
	MeetingTime      *gtime.Time //
	StartTime        *gtime.Time //
	EndTime          *gtime.Time //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
