// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVoteItem is the golang structure of table meeting_vote_item for DAO operations like Where/Data.
type MeetingVoteItem struct {
	g.Meta               `orm:"table:meeting_vote_item, do:true"`
	Id                   interface{} //
	Name                 interface{} //
	IsMultiple           interface{} //
	IsTruename           interface{} //
	IsLimit              interface{} //
	IsLimitVal           interface{} //
	IsRate               interface{} //
	IsRateVal            interface{} //
	MoreThan             interface{} //
	ScreenMode           interface{} //
	ItemJson             interface{} //
	IsRemark             interface{} //
	VotingAuthentication interface{} //
	IsNumberMic          interface{} //
	CreatedAt            *gtime.Time //
	UpdatedAt            *gtime.Time //
}
