// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVote is the golang structure of table meeting_vote for DAO operations like Where/Data.
type MeetingVote struct {
	g.Meta               `orm:"table:meeting_vote, do:true"`
	Id                   interface{} //
	Uuid                 interface{} //
	PlatformUuid         interface{} //
	MeetingUuid          interface{} //
	MeetingDatumUuid     interface{} //
	SystemFileUuid       interface{} //
	VoteTitle            interface{} //
	VoteName             interface{} //
	StartTime            *gtime.Time //
	EndTime              *gtime.Time //
	Countdown            interface{} //
	VoteType             interface{} //
	IsMultiple           interface{} //
	IsTruename           interface{} //
	Status               interface{} //
	Mark                 interface{} //
	IsSign               interface{} //
	IsPassRate           interface{} //
	PassRate             interface{} //
	IsVoteTimeLimit      interface{} //
	VoteTimeLimit        interface{} //
	IsMark               interface{} //
	ScreenMode           interface{} //
	VotingAuthentication interface{} //
	VotingForce          interface{} //
	ScoreScore           interface{} //
	ScoreType            interface{} //
	IsSetting            interface{} //
	RandomSort           interface{} //
	ForceVote            interface{} //
	AutoEnd              interface{} //
	EditResult           interface{} //
	CountVotes           interface{} //
	CreatedAt            *gtime.Time //
	UpdatedAt            *gtime.Time //
}
