// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingVoteOption is the golang structure of table meeting_vote_option for DAO operations like Where/Data.
type MeetingVoteOption struct {
	g.Meta          `orm:"table:meeting_vote_option, do:true"`
	Id              interface{} //
	Uuid            interface{} //
	PlatformUuid    interface{} //
	MeetingVoteUuid interface{} //
	Sort            interface{} //
	VoteOptionName  interface{} //
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
}
