// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingChat is the golang structure of table meeting_chat for DAO operations like Where/Data.
type MeetingChat struct {
	g.Meta      `orm:"table:meeting_chat, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	UserUuid    interface{} //
	MessageType interface{} //
	Type        interface{} //
	Content     interface{} //
	SendTime    *gtime.Time //
	AcceptUuid  interface{} //
	Mark        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
