// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingQueue is the golang structure of table meeting_queue for DAO operations like Where/Data.
type MeetingQueue struct {
	g.Meta      `orm:"table:meeting_queue, do:true"`
	Id          interface{} // 配置id
	MeetingUuid interface{} // 会议uuid，meeting表的uuid
	Status      interface{} // 状态：0未开始，1开会中，2结束，5执行失败
	EndTime     *gtime.Time // 结束时间
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time // 更新时间
}
