// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingBanner is the golang structure of table meeting_banner for DAO operations like Where/Data.
type MeetingBanner struct {
	g.Meta         `orm:"table:meeting_banner, do:true"`
	Id             interface{} //
	Uuid           interface{} //
	PlatformUuid   interface{} //
	MeetingUuid    interface{} //
	Title          interface{} //
	Background     interface{} //
	ModelFlag      interface{} //
	Datalayout     interface{} //
	Sort           interface{} //
	BackgroundFlag interface{} //
	BigFlag        interface{} //
	SmallFlag      interface{} //
	BannerImg      interface{} //
	PushTerminal   interface{} //
	HtmlFormatId   interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
