// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingService is the golang structure of table meeting_service for DAO operations like Where/Data.
type MeetingService struct {
	g.Meta              `orm:"table:meeting_service, do:true"`
	Id                  interface{} //
	MeetingUuid         interface{} //
	UserUuid            interface{} //
	ServerId            interface{} //
	Content             interface{} //
	Time                *gtime.Time //
	IsConfirm           interface{} //
	Mark                interface{} //
	Status              interface{} //
	LaterHandleUserUuid interface{} //
	HandleUserUuid      interface{} //
	LaterHandleTime     *gtime.Time //
	HandleTime          *gtime.Time //
	DeviceType          interface{} //
	CreatedAt           *gtime.Time //
	UpdatedAt           *gtime.Time //
}
