// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingUser is the golang structure of table meeting_user for DAO operations like Where/Data.
type MeetingUser struct {
	g.Meta              `orm:"table:meeting_user, do:true"`
	Id                  interface{} //
	MeetingUuid         interface{} //
	UserUuid            interface{} //
	TerminalId          interface{} //
	IsBroadcast         interface{} //
	Status              interface{} //
	IsSecretary         interface{} //
	Username            interface{} //
	Nameplate           interface{} //
	IsUpdateNameplate   interface{} //
	IsUpdateWelcomePage interface{} //
	Mark                interface{} //
	FreeLogin           interface{} //
	IsChairman          interface{} //
	IsAttendee          interface{} //
	Sort                interface{} //
	Lifter              interface{} //
	Deleted             interface{} //
	Unit                interface{} //
	Position            interface{} //
	IsLocal             interface{} //
	Alias               interface{} //
	AttendType          interface{} //
	IsAutoQueue         interface{} //
	IsSign              interface{} //
	CreatedAt           *gtime.Time //
	UpdatedAt           *gtime.Time //
}
