// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingSummaryOpinion is the golang structure of table meeting_summary_opinion for DAO operations like Where/Data.
type MeetingSummaryOpinion struct {
	g.Meta           `orm:"table:meeting_summary_opinion, do:true"`
	Id               interface{} //
	MeetingUuid      interface{} //
	UserUuid         interface{} //
	MeetingSummaryId interface{} //
	SendTime         *gtime.Time //
	Content          interface{} //
	Page             interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
