// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingDatum is the golang structure of table meeting_datum for DAO operations like Where/Data.
type MeetingDatum struct {
	g.Meta           `orm:"table:meeting_datum, do:true"`
	Id               interface{} //
	Uuid             interface{} //
	MeetingUuid      interface{} //
	UserUuid         interface{} //
	PlatformUuid     interface{} //
	SystemFileUuid   interface{} //
	Name             interface{} //
	Status           interface{} //
	Sort             interface{} //
	Mark             interface{} //
	Reporter         interface{} //
	ReportTime       interface{} //
	IsJoinVote       interface{} //
	IsSecret         interface{} //
	StartTime        *gtime.Time //
	EndTime          *gtime.Time //
	PushTime         interface{} //
	PushStatus       interface{} //
	StartDatum       interface{} //
	RoomSeatSchemeId interface{} //
	ReporterField    interface{} //
	UserShow         interface{} //
	Attendee         interface{} //
	UserDefined      interface{} //
	AttendeeField    interface{} //
	ReporterShow     interface{} //
	UnitShow         interface{} //
	UnitField        interface{} //
	Unit             interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
