// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingFileFormat is the golang structure of table meeting_file_format for DAO operations like Where/Data.
type MeetingFileFormat struct {
	g.Meta      `orm:"table:meeting_file_format, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	UserUuid    interface{} //
	Url         interface{} //
	Path        interface{} //
	Progress    interface{} //
	Status      interface{} //
	Time        *gtime.Time //
	Type        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
