// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingRecordContent is the golang structure of table meeting_record_content for DAO operations like Where/Data.
type MeetingRecordContent struct {
	g.Meta      `orm:"table:meeting_record_content, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	TerminalId  interface{} //
	HtmlContent interface{} //
	WordContent interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
