// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MeetingExtra is the golang structure of table meeting_extra for DAO operations like Where/Data.
type MeetingExtra struct {
	g.Meta          `orm:"table:meeting_extra, do:true"`
	MeetingUuid     interface{} //
	MenuTab         interface{} //
	NameplateCustom interface{} //
	WelcomeCustom   interface{} //
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
}
