// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Meeting is the golang structure of table meeting for DAO operations like Where/Data.
type Meeting struct {
	g.Meta           `orm:"table:meeting, do:true"`
	Id               interface{} //
	PlatformUuid     interface{} //
	Uuid             interface{} //
	UserUuid         interface{} //
	Name             interface{} //
	Type             interface{} //
	Moderator        interface{} //
	Secretary        interface{} //
	StartTime        *gtime.Time //
	EndTime          *gtime.Time //
	RealStartTime    *gtime.Time //
	RealEndTime      *gtime.Time //
	MasterRoomId     interface{} //
	RoomListId       interface{} //
	MeetingSlogan    interface{} //
	Nameplate        interface{} //
	Status           interface{} //
	IsSecrect        interface{} //
	Description      interface{} //
	AllUser          interface{} //
	ModeratorName    interface{} //
	MeetingType      interface{} //
	IsHost           interface{} //
	HostMeetingUuid  interface{} //
	HostPlatformUuid interface{} //
	HostIp           interface{} //
	HostPsIp         interface{} //
	HostPsPort       interface{} //
	MenuData         interface{} //
	MenuTab          interface{} //
	NameplateCustom  interface{} //
	WelcomeCustom    interface{} //
	CustomBgImg      interface{} //
	Deleted          interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
