// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MicrophoneServerTerminal is the golang structure of table microphone_server_terminal for DAO operations like Where/Data.
type MicrophoneServerTerminal struct {
	g.Meta             `orm:"table:microphone_server_terminal, do:true"`
	Id                 interface{} //
	MicId              interface{} //
	Type               interface{} //
	Status             interface{} //
	MicrophoneServerId interface{} //
	Mark               interface{} //
	Mac                interface{} //
	ScreenIp           interface{} //
	DataType           interface{} // 1:普通话筒，2:8512
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
}
