// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MicrophoneServer is the golang structure of table microphone_server for DAO operations like Where/Data.
type MicrophoneServer struct {
	g.Meta      `orm:"table:microphone_server, do:true"`
	Id          interface{} //
	RoomId      interface{} //
	Ip          interface{} //
	Port        interface{} //
	MicMax      interface{} //
	MicType     interface{} //
	Volume      interface{} //
	Alt         interface{} //
	Bass        interface{} //
	Sensitivity interface{} //
	ClosingTime interface{} //
	Mark        interface{} //
	HostSn      interface{} //
	Status      interface{} //
	Register    interface{} //
	DeviceType  interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
