// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OperationLog is the golang structure of table operation_log for DAO operations like Where/Data.
type OperationLog struct {
	g.Meta        `orm:"table:operation_log, do:true"`
	Id            interface{} //
	UserUuid      interface{} //
	Module        interface{} //
	Operation     interface{} //
	OperationType interface{} //
	Detail        interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
