// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Organization is the golang structure of table organization for DAO operations like Where/Data.
type Organization struct {
	g.Meta       `orm:"table:organization, do:true"`
	Id           interface{} //
	Uuid         interface{} //
	Puuid        interface{} //
	PlatformUuid interface{} //
	Level        interface{} //
	Name         interface{} //
	Sort         interface{} //
	IsTmp        interface{} //
	Status       interface{} //
	Deleted      interface{} //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
