// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Platform is the golang structure of table platform for DAO operations like Where/Data.
type Platform struct {
	g.Meta    `orm:"table:platform, do:true"`
	Id        interface{} //
	Uuid      interface{} //
	Name      interface{} //
	IsLocal   interface{} //
	Sysip     interface{} //
	Sysport   interface{} //
	Sysid     interface{} //
	Status    interface{} //
	Enable    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
