// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PlatformPushTask is the golang structure of table platform_push_task for DAO operations like Where/Data.
type PlatformPushTask struct {
	g.Meta       `orm:"table:platform_push_task, do:true"`
	Id           interface{} //
	PlatformUuid interface{} //
	MeetingUuid  interface{} //
	Status       interface{} //
	Operate      interface{} //
	JoinTime     *gtime.Time //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
