// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PositionType is the golang structure of table position_type for DAO operations like Where/Data.
type PositionType struct {
	g.Meta    `orm:"table:position_type, do:true"`
	Id        interface{} //
	Name      interface{} //
	Sort      interface{} //
	Deleted   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
