// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Position is the golang structure of table position for DAO operations like Where/Data.
type Position struct {
	g.Meta         `orm:"table:position, do:true"`
	Id             interface{} //
	PositionTypeId interface{} //
	Name           interface{} //
	Sort           interface{} //
	Deleted        interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
