// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Register is the golang structure of table register for DAO operations like Where/Data.
type Register struct {
	g.Meta    `orm:"table:register, do:true"`
	Id        interface{} //
	Content   interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
