// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSeat is the golang structure of table room_seat for DAO operations like Where/Data.
type RoomSeat struct {
	g.Meta           `orm:"table:room_seat, do:true"`
	Id               interface{} //
	RoomId           interface{} //
	UserUuid         interface{} //
	RoomMicrophoneId interface{} //
	TerminalId       interface{} //
	LifterTerminalId interface{} //
	ElectronicId     interface{} //
	SeatNo           interface{} //
	Title            interface{} //
	Status           interface{} //
	Xway             interface{} //
	Yway             interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
}
