// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomAppointment is the golang structure of table room_appointment for DAO operations like Where/Data.
type RoomAppointment struct {
	g.Meta      `orm:"table:room_appointment, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	UserUuid    interface{} //
	RoomId      interface{} //
	Name        interface{} //
	StartTime   *gtime.Time //
	EndTime     *gtime.Time //
	Status      interface{} //
	Note        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
