// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Room is the golang structure of table room for DAO operations like Where/Data.
type Room struct {
	g.Meta         `orm:"table:room, do:true"`
	Id             interface{} //
	Name           interface{} //
	ServerId       interface{} //
	Roomlayout     interface{} //
	Status         interface{} //
	Mark           interface{} //
	Roombackground interface{} //
	BgWidth        interface{} //
	BgHeight       interface{} //
	TerminalConfig interface{} //
	Transfer       interface{} //
	Electronic     interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
