// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSeatScheme is the golang structure of table room_seat_scheme for DAO operations like Where/Data.
type RoomSeatScheme struct {
	g.Meta      `orm:"table:room_seat_scheme, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	Title       interface{} //
	Type        interface{} //
	Status      interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
