// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoomSetting is the golang structure of table room_setting for DAO operations like Where/Data.
type RoomSetting struct {
	g.Meta    `orm:"table:room_setting, do:true"`
	Id        interface{} //
	RoomId    interface{} //
	Type      interface{} //
	Content   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
