// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Server is the golang structure of table server for DAO operations like Where/Data.
type Server struct {
	g.Meta    `orm:"table:server, do:true"`
	Id        interface{} //
	ServerId  interface{} //
	Ip        interface{} //
	Port      interface{} //
	Status    interface{} //
	Flag      interface{} //
	Mark      interface{} //
	Pid       interface{} //
	Operate   interface{} //
	Auth      interface{} //
	Deleted   interface{} //
	Name      interface{} //
	Content   interface{} //
	IsHost    interface{} //
	UvId      interface{} //
	UvName    interface{} //
	UvStatus  interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
