// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemBackups is the golang structure of table system_backups for DAO operations like Where/Data.
type SystemBackups struct {
	g.Meta     `orm:"table:system_backups, do:true"`
	Id         interface{} //
	Name       interface{} //
	CreateTime *gtime.Time //
	Time       *gtime.Time //
	FileSize   interface{} //
	Type       interface{} //
	Status     interface{} //
	Path       interface{} //
	SqlPath    interface{} //
	Mark       interface{} //
	CurrentUse interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
