// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemFormat is the golang structure of table system_format for DAO operations like Where/Data.
type SystemFormat struct {
	g.Meta       `orm:"table:system_format, do:true"`
	Id           interface{} //
	Type         interface{} //
	UploadSize   interface{} //
	Size         interface{} //
	SystemFormat interface{} //
	DefineFormat interface{} //
	Name         interface{} //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
