// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SystemFile is the golang structure of table system_file for DAO operations like Where/Data.
type SystemFile struct {
	g.Meta        `orm:"table:system_file, do:true"`
	Id            interface{} //
	ParentUuid    interface{} //
	Uuid          interface{} //
	PlatformUuid  interface{} //
	MeetingUuid   interface{} //
	UserUuid      interface{} //
	Filename      interface{} //
	Filesize      interface{} //
	Filepath      interface{} //
	TerminalId    interface{} //
	UploadTime    *gtime.Time //
	Sort          interface{} //
	FileUse       interface{} //
	Mark          interface{} //
	IsDirectory   interface{} //
	AllUser       interface{} //
	StartDatum    interface{} //
	AllowDownload interface{} //
	IsSecret      interface{} //
	Status        interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
