// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskQueue is the golang structure of table task_queue for DAO operations like Where/Data.
type TaskQueue struct {
	g.Meta      `orm:"table:task_queue, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	Inst        interface{} //
	ServerId    interface{} //
	InsertTime  *gtime.Time //
	ExecTime    *gtime.Time //
	Sort        interface{} //
	Content     interface{} //
	Status      interface{} //
	Mark        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
