// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Terminal is the golang structure of table terminal for DAO operations like Where/Data.
type Terminal struct {
	g.Meta                  `orm:"table:terminal, do:true"`
	Id                      interface{} //
	TId                     interface{} //
	Name                    interface{} //
	Ip                      interface{} //
	Mac                     interface{} //
	Status                  interface{} //
	RoomId                  interface{} //
	Mark                    interface{} //
	Type                    interface{} //
	Config                  interface{} //
	ConfigStatus            interface{} //
	AssociatedVersionId     interface{} //
	AssociatedVersionName   interface{} //
	AssociatedVersionStatus interface{} //
	Operate                 interface{} //
	OsType                  interface{} //
	GuardConfig             interface{} //
	GuardUvId               interface{} //
	GuardUvName             interface{} //
	GuardUvStatus           interface{} //
	DeviceSn                interface{} //
	DeviceType              interface{} //
	IpType                  interface{} //
	Mask                    interface{} //
	Gateway                 interface{} //
	HostIp                  interface{} //
	ClientIp                interface{} //
	OptCounts               interface{} //
	Concurrence             interface{} //
	LifterType              interface{} //
	SecondTid               interface{} //
	CreatedAt               *gtime.Time //
	UpdatedAt               *gtime.Time //
}
