// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TerminalConcurrence is the golang structure of table terminal_concurrence for DAO operations like Where/Data.
type TerminalConcurrence struct {
	g.Meta      `orm:"table:terminal_concurrence, do:true"`
	Id          interface{} //
	MeetingUuid interface{} //
	TotalUser   interface{} //
	ClientIds   interface{} //
	Usernames   interface{} //
	UserMax     interface{} //
	Type        interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
