// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPosition is the golang structure of table user_position for DAO operations like Where/Data.
type UserPosition struct {
	g.Meta     `orm:"table:user_position, do:true"`
	Id         interface{} //
	UserUuid   interface{} //
	PositionId interface{} //
	Default    interface{} //
	Deleted    interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
