// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOtherLogin is the golang structure of table user_other_login for DAO operations like Where/Data.
type UserOtherLogin struct {
	g.Meta    `orm:"table:user_other_login, do:true"`
	Id        interface{} //
	UserUuid  interface{} //
	Name      interface{} //
	Pass      interface{} //
	Type      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
