// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserFile is the golang structure of table user_file for DAO operations like Where/Data.
type UserFile struct {
	g.Meta         `orm:"table:user_file, do:true"`
	MeetingUuid    interface{} //
	UserUuid       interface{} //
	SystemFileUuid interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
