// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserFingerPrint is the golang structure of table user_finger_print for DAO operations like Where/Data.
type UserFingerPrint struct {
	g.Meta      `orm:"table:user_finger_print, do:true"`
	Id          interface{} //
	UserUuid    interface{} //
	Finger      interface{} //
	Fingerprint interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
