// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// VideoFormat is the golang structure of table video_format for DAO operations like Where/Data.
type VideoFormat struct {
	g.Meta         `orm:"table:video_format, do:true"`
	Id             interface{} //
	SystemFileUuid interface{} //
	Progress       interface{} //
	Status         interface{} //
	Path           interface{} //
	Type           interface{} //
	Force          interface{} //
	Remain         *gtime.Time //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
}
