server:
  address:     ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    type: "mysql"
    link: "root:Rootitc123!@tcp(172.16.19.47:3108)/paperless?loc=Local&parseTime=true"
    debug: true
    createdAt: "created_at"
    updatedAt: "updated_at"
  logger:
    path: "./log/sql"
    file: "sql-{Y-m-d}.log"
    level: "all"
    stdout: false
    Flags: 32



