
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
[gfcli]
  [gfcli.gen]
    [gfcli.gen.dao]
       link = "mysql:root:Rootitc123!@tcp(172.16.19.47:3108)/paperless"