// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalConfigThemeDao is internal type for wrapping internal DAO implements.
type internalConfigThemeDao = *internal.ConfigThemeDao

// configThemeDao is the data access object for table config_theme.
// You can define custom methods on it to extend its functionality as you wish.
type configThemeDao struct {
	internalConfigThemeDao
}

var (
	// ConfigTheme is globally public accessible object for table config_theme operations.
	ConfigTheme = configThemeDao{
		internal.NewConfigThemeDao(),
	}
)

// Fill with you ideas below.
