// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalDeviceMsgDao is internal type for wrapping internal DAO implements.
type internalDeviceMsgDao = *internal.DeviceMsgDao

// deviceMsgDao is the data access object for table device_msg.
// You can define custom methods on it to extend its functionality as you wish.
type deviceMsgDao struct {
	internalDeviceMsgDao
}

var (
	// DeviceMsg is globally public accessible object for table device_msg operations.
	DeviceMsg = deviceMsgDao{
		internal.NewDeviceMsgDao(),
	}
)

// Fill with you ideas below.
