// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalFileFormatDao is internal type for wrapping internal DAO implements.
type internalFileFormatDao = *internal.FileFormatDao

// fileFormatDao is the data access object for table file_format.
// You can define custom methods on it to extend its functionality as you wish.
type fileFormatDao struct {
	internalFileFormatDao
}

var (
	// FileFormat is globally public accessible object for table file_format operations.
	FileFormat = fileFormatDao{
		internal.NewFileFormatDao(),
	}
)

// Fill with you ideas below.
