// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalLivePushDao is internal type for wrapping internal DAO implements.
type internalLivePushDao = *internal.LivePushDao

// livePushDao is the data access object for table live_push.
// You can define custom methods on it to extend its functionality as you wish.
type livePushDao struct {
	internalLivePushDao
}

var (
	// LivePush is globally public accessible object for table live_push operations.
	LivePush = livePushDao{
		internal.NewLivePushDao(),
	}
)

// Fill with you ideas below.
