// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingStatisticsDao is internal type for wrapping internal DAO implements.
type internalMeetingStatisticsDao = *internal.MeetingStatisticsDao

// meetingStatisticsDao is the data access object for table meeting_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type meetingStatisticsDao struct {
	internalMeetingStatisticsDao
}

var (
	// MeetingStatistics is globally public accessible object for table meeting_statistics operations.
	MeetingStatistics = meetingStatisticsDao{
		internal.NewMeetingStatisticsDao(),
	}
)

// Fill with you ideas below.
