// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingQueueDao is internal type for wrapping internal DAO implements.
type internalMeetingQueueDao = *internal.MeetingQueueDao

// meetingQueueDao is the data access object for table meeting_queue.
// You can define custom methods on it to extend its functionality as you wish.
type meetingQueueDao struct {
	internalMeetingQueueDao
}

var (
	// MeetingQueue is globally public accessible object for table meeting_queue operations.
	MeetingQueue = meetingQueueDao{
		internal.NewMeetingQueueDao(),
	}
)

// Fill with you ideas below.
