// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingSignInfoDao is internal type for wrapping internal DAO implements.
type internalMeetingSignInfoDao = *internal.MeetingSignInfoDao

// meetingSignInfoDao is the data access object for table meeting_sign_info.
// You can define custom methods on it to extend its functionality as you wish.
type meetingSignInfoDao struct {
	internalMeetingSignInfoDao
}

var (
	// MeetingSignInfo is globally public accessible object for table meeting_sign_info operations.
	MeetingSignInfo = meetingSignInfoDao{
		internal.NewMeetingSignInfoDao(),
	}
)

// Fill with you ideas below.
