// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingUserRightsDao is internal type for wrapping internal DAO implements.
type internalMeetingUserRightsDao = *internal.MeetingUserRightsDao

// meetingUserRightsDao is the data access object for table meeting_user_rights.
// You can define custom methods on it to extend its functionality as you wish.
type meetingUserRightsDao struct {
	internalMeetingUserRightsDao
}

var (
	// MeetingUserRights is globally public accessible object for table meeting_user_rights operations.
	MeetingUserRights = meetingUserRightsDao{
		internal.NewMeetingUserRightsDao(),
	}
)

// Fill with you ideas below.
