// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingUserDao is internal type for wrapping internal DAO implements.
type internalMeetingUserDao = *internal.MeetingUserDao

// meetingUserDao is the data access object for table meeting_user.
// You can define custom methods on it to extend its functionality as you wish.
type meetingUserDao struct {
	internalMeetingUserDao
}

var (
	// MeetingUser is globally public accessible object for table meeting_user operations.
	MeetingUser = meetingUserDao{
		internal.NewMeetingUserDao(),
	}
)

// Fill with you ideas below.
