// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingSummaryOpinionDao is internal type for wrapping internal DAO implements.
type internalMeetingSummaryOpinionDao = *internal.MeetingSummaryOpinionDao

// meetingSummaryOpinionDao is the data access object for table meeting_summary_opinion.
// You can define custom methods on it to extend its functionality as you wish.
type meetingSummaryOpinionDao struct {
	internalMeetingSummaryOpinionDao
}

var (
	// MeetingSummaryOpinion is globally public accessible object for table meeting_summary_opinion operations.
	MeetingSummaryOpinion = meetingSummaryOpinionDao{
		internal.NewMeetingSummaryOpinionDao(),
	}
)

// Fill with you ideas below.
