// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMeetingExtraDao is internal type for wrapping internal DAO implements.
type internalMeetingExtraDao = *internal.MeetingExtraDao

// meetingExtraDao is the data access object for table meeting_extra.
// You can define custom methods on it to extend its functionality as you wish.
type meetingExtraDao struct {
	internalMeetingExtraDao
}

var (
	// MeetingExtra is globally public accessible object for table meeting_extra operations.
	MeetingExtra = meetingExtraDao{
		internal.NewMeetingExtraDao(),
	}
)

// Fill with you ideas below.
