// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalMonitoringDao is internal type for wrapping internal DAO implements.
type internalMonitoringDao = *internal.MonitoringDao

// monitoringDao is the data access object for table monitoring.
// You can define custom methods on it to extend its functionality as you wish.
type monitoringDao struct {
	internalMonitoringDao
}

var (
	// Monitoring is globally public accessible object for table monitoring operations.
	Monitoring = monitoringDao{
		internal.NewMonitoringDao(),
	}
)

// Fill with you ideas below.
