// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalOrganizationDao is internal type for wrapping internal DAO implements.
type internalOrganizationDao = *internal.OrganizationDao

// organizationDao is the data access object for table organization.
// You can define custom methods on it to extend its functionality as you wish.
type organizationDao struct {
	internalOrganizationDao
}

var (
	// Organization is globally public accessible object for table organization operations.
	Organization = organizationDao{
		internal.NewOrganizationDao(),
	}
)

// Fill with you ideas below.
