// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalPhoneticTranscriptionLogDao is internal type for wrapping internal DAO implements.
type internalPhoneticTranscriptionLogDao = *internal.PhoneticTranscriptionLogDao

// phoneticTranscriptionLogDao is the data access object for table phonetic_transcription_log.
// You can define custom methods on it to extend its functionality as you wish.
type phoneticTranscriptionLogDao struct {
	internalPhoneticTranscriptionLogDao
}

var (
	// PhoneticTranscriptionLog is globally public accessible object for table phonetic_transcription_log operations.
	PhoneticTranscriptionLog = phoneticTranscriptionLogDao{
		internal.NewPhoneticTranscriptionLogDao(),
	}
)

// Fill with you ideas below.
