// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalPlatformPushTaskDao is internal type for wrapping internal DAO implements.
type internalPlatformPushTaskDao = *internal.PlatformPushTaskDao

// platformPushTaskDao is the data access object for table platform_push_task.
// You can define custom methods on it to extend its functionality as you wish.
type platformPushTaskDao struct {
	internalPlatformPushTaskDao
}

var (
	// PlatformPushTask is globally public accessible object for table platform_push_task operations.
	PlatformPushTask = platformPushTaskDao{
		internal.NewPlatformPushTaskDao(),
	}
)

// Fill with you ideas below.
