// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalPlatformDao is internal type for wrapping internal DAO implements.
type internalPlatformDao = *internal.PlatformDao

// platformDao is the data access object for table platform.
// You can define custom methods on it to extend its functionality as you wish.
type platformDao struct {
	internalPlatformDao
}

var (
	// Platform is globally public accessible object for table platform operations.
	Platform = platformDao{
		internal.NewPlatformDao(),
	}
)

// Fill with you ideas below.
