// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalPositionTypeDao is internal type for wrapping internal DAO implements.
type internalPositionTypeDao = *internal.PositionTypeDao

// positionTypeDao is the data access object for table position_type.
// You can define custom methods on it to extend its functionality as you wish.
type positionTypeDao struct {
	internalPositionTypeDao
}

var (
	// PositionType is globally public accessible object for table position_type operations.
	PositionType = positionTypeDao{
		internal.NewPositionTypeDao(),
	}
)

// Fill with you ideas below.
