// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalRecordingFileDao is internal type for wrapping internal DAO implements.
type internalRecordingFileDao = *internal.RecordingFileDao

// recordingFileDao is the data access object for table recording_file.
// You can define custom methods on it to extend its functionality as you wish.
type recordingFileDao struct {
	internalRecordingFileDao
}

var (
	// RecordingFile is globally public accessible object for table recording_file operations.
	RecordingFile = recordingFileDao{
		internal.NewRecordingFileDao(),
	}
)

// Fill with you ideas below.
