// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalRoomAppointmentDao is internal type for wrapping internal DAO implements.
type internalRoomAppointmentDao = *internal.RoomAppointmentDao

// roomAppointmentDao is the data access object for table room_appointment.
// You can define custom methods on it to extend its functionality as you wish.
type roomAppointmentDao struct {
	internalRoomAppointmentDao
}

var (
	// RoomAppointment is globally public accessible object for table room_appointment operations.
	RoomAppointment = roomAppointmentDao{
		internal.NewRoomAppointmentDao(),
	}
)

// Fill with you ideas below.
