// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalRoomSettingServeDao is internal type for wrapping internal DAO implements.
type internalRoomSettingServeDao = *internal.RoomSettingServeDao

// roomSettingServeDao is the data access object for table room_setting_serve.
// You can define custom methods on it to extend its functionality as you wish.
type roomSettingServeDao struct {
	internalRoomSettingServeDao
}

var (
	// RoomSettingServe is globally public accessible object for table room_setting_serve operations.
	RoomSettingServe = roomSettingServeDao{
		internal.NewRoomSettingServeDao(),
	}
)

// Fill with you ideas below.
