// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalTerminalConcurrenceDao is internal type for wrapping internal DAO implements.
type internalTerminalConcurrenceDao = *internal.TerminalConcurrenceDao

// terminalConcurrenceDao is the data access object for table terminal_concurrence.
// You can define custom methods on it to extend its functionality as you wish.
type terminalConcurrenceDao struct {
	internalTerminalConcurrenceDao
}

var (
	// TerminalConcurrence is globally public accessible object for table terminal_concurrence operations.
	TerminalConcurrence = terminalConcurrenceDao{
		internal.NewTerminalConcurrenceDao(),
	}
)

// Fill with you ideas below.
