// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalUpgradeVersionDao is internal type for wrapping internal DAO implements.
type internalUpgradeVersionDao = *internal.UpgradeVersionDao

// upgradeVersionDao is the data access object for table upgrade_version.
// You can define custom methods on it to extend its functionality as you wish.
type upgradeVersionDao struct {
	internalUpgradeVersionDao
}

var (
	// UpgradeVersion is globally public accessible object for table upgrade_version operations.
	UpgradeVersion = upgradeVersionDao{
		internal.NewUpgradeVersionDao(),
	}
)

// Fill with you ideas below.
