// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalUserOtherLoginDao is internal type for wrapping internal DAO implements.
type internalUserOtherLoginDao = *internal.UserOtherLoginDao

// userOtherLoginDao is the data access object for table user_other_login.
// You can define custom methods on it to extend its functionality as you wish.
type userOtherLoginDao struct {
	internalUserOtherLoginDao
}

var (
	// UserOtherLogin is globally public accessible object for table user_other_login operations.
	UserOtherLogin = userOtherLoginDao{
		internal.NewUserOtherLoginDao(),
	}
)

// Fill with you ideas below.
