// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo1/internal/dao/internal"
)

// internalUserPositionDao is internal type for wrapping internal DAO implements.
type internalUserPositionDao = *internal.UserPositionDao

// userPositionDao is the data access object for table user_position.
// You can define custom methods on it to extend its functionality as you wish.
type userPositionDao struct {
	internalUserPositionDao
}

var (
	// UserPosition is globally public accessible object for table user_position operations.
	UserPosition = userPositionDao{
		internal.NewUserPositionDao(),
	}
)

// Fill with you ideas below.
